"""Crystallizer — turn verified Q&A and failure traces into Crystal rows.

Phase 0.2 of the bind-storage rebuild (docs/BIND_STORAGE_REBUILD.md).
Ports the GAIA stand-in's logic (experiments/gaia/crystallizer.py) into
production code. The math is unchanged; the IO surface and invariants
are tightened for a real product.

WHAT THIS MODULE DOES
---------------------

1. crystallize_success(...): a verified-correct prior answer becomes a
   `model_reasoning` Crystal carrying both the prose answer (for
   text-injection on a future match) and a short `answer_value` (for
   the cache short-circuit on a PERFECT match).

2. crystallize_failure(...): a wrong attempt becomes a `failed_reasoning`
   Crystal whose payload is an IMPERATIVE RULE — one or two sentences
   in imperative voice that would have prevented the failure. The rule
   is generated by one Haiku call (the reflection_client). On any
   reflection error, fallback to the raw end-truncated trace per the
   GAIA stand-in.

3. Tool-output extraction: `extract_web_search_provenance` and
   `extract_code_exec_output` ported verbatim. These produce additional
   crystals for the success path only — we don't trust tool framing on
   a wrong reasoning chain (the model may have searched the wrong
   thing; storing those URLs would route future similar queries toward
   the same wrong source path).

WHAT CHANGES VS. THE GAIA STAND-IN
----------------------------------

- Inputs are production shape. GAIA had `GaiaQuestion` + `AnsweredQuestion`
  with `match_normalized` and `expected_answer`. Production has none of
  those concepts: a customer's pipeline doesn't have ground truth at
  request time. The crystallizer's caller MUST assert that an answer is
  verified before calling `crystallize_success`. The crystallizer
  refuses to derive verification — that's a benchmark concept, not a
  production one.

- Outputs are persisted to MetadataStore, not returned as dataclasses.
  GAIA returned `list[FactCrystal]` for batched bank-build; production
  writes one (or a few) Crystal rows per call.

- The reflection client goes through the provider-neutral seam
  (get_llm_client). An optional override can still be injected — tests
  pass a fake exposing complete(...) — but no caller constructs a raw
  client anymore.

- Crystals get `customer_id` scope. GAIA had no tenant scope.

- Encoder access is required: the crystallizer encodes prompt_text into
  `summary_vector` and answer_text into `answer_embedding_native` at
  write time, mirroring `import_bank.py`. Phase 1.1 will replace this
  with bind-bundle math; the public API of the crystallizer will not
  change.

INVARIANTS (Rule 5 / Rule 13)
-----------------------------

- `crystallize_success` requires `verified_correct=True` from the caller.
  Any other value raises ValueError. We do not have an in-process
  signal that an answer is correct; production callers obtain that
  signal from explicit thumbs-up feedback, automated assertion, or
  human review.

- `crystallize_success` does NOT enforce a minimum-length floor on the
  answer. The verified-correct flag IS the signal that the answer is
  worth keeping. A 5-char verified answer ("Paris") is just as valid
  as a 500-char verified answer. GAIA had a 50-char floor because GAIA
  was crystallizing model REASONING TRACES (which are noise below 50
  chars); production crystallizes verified Q&A pairs, where short is
  fine.

- `crystallize_failure` requires both `wrong_answer` and `failed_reasoning`
  to be non-empty. A failure crystal authored from empty inputs would
  produce a useless reflection. The failure path also keeps a small
  fallback floor (`_MIN_FALLBACK_CHARS = 10`) on the raw-trace fallback
  branch only — if reflection failed AND the trace is under 10 chars,
  there's nothing useful to inject.

- Tool-output crystals (web search results, code execution stdout)
  enforce a `_MIN_TOOL_CONTENT_CHARS = 30` floor. This is intentionally
  lower than GAIA's 50 because real production web-search titles plus
  URLs land in the 30-60 char range. Below 30 chars the content is
  genuinely empty noise (a single-word title + a domain-only URL).

- Fact rows are NOT written by Phase 0.2. The crystallizer creates
  Crystal rows whose `summary_vector` carries the prompt-projection
  and `answer_embedding_native` carries the answer's native embedding.
  Phase 1.1 will additionally call `metadata_store.add_pair_to_crystal`
  to populate the codebook; the crystallizer's public interface won't
  change.
"""
from __future__ import annotations

import re
import json
import uuid
from dataclasses import dataclass
from typing import Any, Iterable, Optional, Protocol

import structlog

from ..llm import get_llm_client
from ..encoding.base import TextEncoder
from ..encoding.executor import run_encoder_bound
from ..infrastructure.metadata_store import MetadataStore
from ..models import Crystal


logger = structlog.get_logger(__name__)


# ---------------------------------------------------------------------------
# Tunables (mirror experiments/gaia/crystallizer.py)
# ---------------------------------------------------------------------------

# Maximum content length for a single crystal. Long crystals dilute
# routing — a 10k-char crystal will match weakly against many queries
# rather than strongly against one. 4000 chars is ~1000 tokens.
_MAX_CONTENT_CHARS = 4000

# Minimum length below which a TOOL-DERIVED crystal (web search,
# code execution) is too short to carry routing signal. Title+url
# pairs and stdout snippets that don't clear this bar get skipped.
# Does NOT apply to crystallize_success's reasoning crystal (the
# verified flag is the signal there) or to crystallize_failure's
# reflection (which has its own length cap inside the reflector).
#
# 30 chars is the working floor. Realistic web-search results have
# short titles ("Paris - Wikipedia", "ESPN.com") and short URLs
# ("https://espn.com/nba"); a "Title — URL" composite below 30 chars
# is genuinely empty noise (a single-word title + a domain-only URL).
# GAIA's original 50-char threshold inherited the value from its
# reasoning-trace floor without re-justifying it for tool outputs;
# real production results land in the 30-60 char range. This is the
# same lesson as the success-path verified-correct fix in Phase 0.2 —
# GAIA-shaped thresholds need re-justification when ported to
# production tool-output code paths.
_MIN_TOOL_CONTENT_CHARS = 30

# Minimum length for the failure-path raw-trace FALLBACK only. If the
# reflection client produced no usable rule and the trace itself is
# shorter than this, there's nothing worth crystallizing.
_MIN_FALLBACK_CHARS = 10

# Reflection generation budget. Reflections must be SHORT — one or two
# sentences, imperative voice, transferable rule. Token cap forces brevity.
_REFLECTION_MAX_TOKENS = 200

# How much of the failed trace to feed the reflector. The END of the
# trace is more diagnostic than the start (the conclusion is where the
# failure mode crystallizes). 3000 chars ~750 tokens.
_REFLECTION_TRACE_BUDGET = 3000


# ---------------------------------------------------------------------------
# Reflection client protocol
# ---------------------------------------------------------------------------

class ReflectionClient(Protocol):
    """Minimal Protocol for an optional reflection-client override.

    Satisfied by the provider-neutral LLMClient (exposes complete(...)) and by
    the test fake. When no override is passed the crystallizer uses the seam
    via get_llm_client, so a raw anthropic client is no longer the shape here.
    """

    def complete(self, **kwargs: Any) -> str:  # pragma: no cover - Protocol stub
        ...


# ---------------------------------------------------------------------------
# Reflection prompt (verbatim from GAIA — see experiments/gaia/crystallizer.py)
# ---------------------------------------------------------------------------

# Framing rationale (recap):
#   - "transferable rule" not "explanation" — output must be usable as
#     a constraint on a future attempt, not a post-mortem.
#   - imperative voice — what the literature found injects most cleanly
#     into next-attempt prompts (Reflexion, Shinn et al. 2023; ERL 2026;
#     RBB-LLM Nature 2025).
#   - "applicable to similar questions" — we may inject this rule to a
#     different but related query, not just the literal same one.
#   - explicit length cap in the prompt — model otherwise tends toward
#     three-paragraph reflections.
#
# Output is plain text (no JSON, no labels) so it can drop directly
# into the crystal's payload without parsing.
_REFLECTION_SYSTEM_PROMPT = """You analyze a failed answer attempt and write ONE imperative rule \
that would have prevented the failure. The rule will be shown to a \
future model attempting a similar question.

Requirements:
- ONE or TWO sentences. No more.
- IMPERATIVE voice ("verify X before Y", "check whether Z", "prefer A \
over B"). NOT explanatory voice ("the model should have...", "you \
failed to...").
- Transferable. Phrase the rule so it applies to the CATEGORY of \
failure, not the literal facts of this question. Good: "When counting \
studio albums, verify each candidate is a studio album (not live, \
compilation, or collaborative) before including it." Bad: "Don't \
include Acústico en vivo."
- No preamble. No "Rule:" prefix. No restating the question.
- Output the rule text only."""


# ---------------------------------------------------------------------------
# Tool output types
# ---------------------------------------------------------------------------

@dataclass
class ToolOutput:
    """Production tool-output shape for the crystallizer.

    Mirrors GAIA's `ToolCall` but is named differently and lives in this
    module to avoid a cross-package import. Production callers (the
    diagnostic loop, the future thumbs-down processor) construct these
    from upstream provider responses.

    Fields match GAIA's surface: name, input dict, output string, optional
    error string. The crystallizer's extractors handle the same provider
    string formats GAIA does.
    """
    name: str
    input: dict[str, Any]
    output: str
    error: Optional[str] = None


# Web search results land in tool output as a stringified list of
# WebSearchResultBlock entries. Each block has visible plaintext fields
# (title, url) plus opaque encrypted content. We pull title + url.
#
# Format (reproduced from GAIA):
#   "[WebSearchResultBlock(encrypted_content='...', page_age=None,
#     title='Some Title', type='web_search_result',
#     url='https://example.com'), WebSearchResultBlock(...)]"
_RE_WEB_TITLE = re.compile(r"title='([^']*)'")
_RE_WEB_URL = re.compile(r"url='([^']*)'")


def extract_web_search_provenance(tool_call: ToolOutput) -> list[tuple[str, str]]:
    """Pull (title, url) pairs out of a web_search ToolOutput.

    Parses the v2 seam shape first (JSON with a results list of
    {title, url, snippet, content} dicts — search/web.py); falls back to
    the v1 block-repr regexes (title='...' / url='...') for legacy
    outputs. Returns [] if the tool wasn't a web_search, output was
    empty, or neither shape matches.
    """
    if tool_call.name != "web_search":
        return []
    if not tool_call.output or tool_call.output == "[]":
        return []

    # v2 seam shape (JSON) first.
    try:
        data = json.loads(tool_call.output)
        if isinstance(data, dict) and "results" in data:
            pairs = [
                (str(r.get("title") or ""), str(r.get("url") or ""))
                for r in (data.get("results") or [])
                if isinstance(r, dict) and r.get("url")
            ]
            return pairs
    except (ValueError, TypeError):
        pass

    # v1 block-repr fallback.
    titles = _RE_WEB_TITLE.findall(tool_call.output)
    urls = _RE_WEB_URL.findall(tool_call.output)
    if len(titles) != len(urls):
        # Malformed — return empty rather than mis-pair.
        return []
    return list(zip(titles, urls))


def extract_code_exec_output(tool_call: ToolOutput) -> Optional[str]:
    """Pull stdout text out of a code_execution ToolOutput.

    Returns None if the call errored, output was empty, or the format
    is unrecognized. Tries to parse the standard
    `CodeExecutionResultBlock(stdout='...', stderr='...', return_code=N)`
    shape first; falls back to the whole output when stdout isn't
    extractable but the output is non-empty.
    """
    if tool_call.name not in ("code_execution", "bash_code_execution"):
        return None
    if tool_call.error:
        return None
    if not tool_call.output:
        return None

    m = re.search(r"stdout='([^']*)'", tool_call.output)
    if m:
        stdout = m.group(1)
        # Unescape common things like \\n -> \n
        try:
            stdout = stdout.encode().decode("unicode_escape")
        except UnicodeDecodeError:
            # If unescape fails (rare; usually means malformed output),
            # use the raw string. Better than crashing the crystallizer
            # on a tool-output edge case.
            pass
        return stdout if stdout.strip() else None
    return tool_call.output if tool_call.output.strip() else None


# ---------------------------------------------------------------------------
# Reflection — generate an imperative rule from a wrong answer
# ---------------------------------------------------------------------------

def _reflect_on_failure(
    *,
    question_text: str,
    failed_reasoning: str,
    wrong_answer: str,
    client: Optional[ReflectionClient] = None,
) -> Optional[str]:
    """One Haiku call to extract a transferable imperative rule.

    Differs from GAIA's version in one place: there's no `expected_answer`.
    Production failures are identified by the user thumbs-down or by
    explicit redirect, not by ground-truth comparison. The reflector
    works fine without an expected answer — the wrong answer plus the
    trace plus the question are enough to identify the failure mode.

    Returns the rule text, or None on any failure (network error,
    empty output, malformed response). Caller handles the None case
    by falling back to the raw trace.
    """
    if not failed_reasoning or not failed_reasoning.strip():
        return None

    trace_tail = failed_reasoning[-_REFLECTION_TRACE_BUDGET:]
    user_message = (
        f"Question:\n{question_text}\n\n"
        f"Wrong answer given: {wrong_answer!r}\n\n"
        f"Tail of the failed reasoning:\n---\n{trace_tail}\n---\n\n"
        f"Write the imperative rule."
    )

    reflect_client = client if client is not None else get_llm_client()
    try:
        rule = reflect_client.complete(
            system=_REFLECTION_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_message}],
            max_tokens=_REFLECTION_MAX_TOKENS,
            temperature=0.0,
            tier="small",
        )
    except Exception as exc:
        # Don't let a reflection failure break crystallization. Log and
        # return None so the caller falls back to the raw trace.
        logger.warning(
            "reflection_call_failed",
            error_type=type(exc).__name__,
            error=str(exc),
        )
        return None

    if not rule:
        return None
    # Defensive cap. If the model ignored the length instruction we don't
    # want a 5kB injection. 600 chars is generous for one or two
    # imperative sentences.
    if len(rule) > 600:
        rule = rule[:600].rstrip()
    return rule


# ---------------------------------------------------------------------------
# Public API — success path
# ---------------------------------------------------------------------------

async def crystallize_success(
    *,
    customer_id: str,
    question_text: str,
    answer_text: str,
    answer_value: Optional[str],
    verified_correct: bool,
    store: MetadataStore,
    encoder: TextEncoder,
    tool_outputs: Optional[Iterable[ToolOutput]] = None,
    quality_tier: str = "neutral",
) -> list[Crystal]:
    """Crystallize a verified-correct (question, answer) pair.

    Writes one `model_reasoning` Crystal carrying the answer text,
    plus optionally additional crystals for web-search provenance and
    code-execution outputs from the same conversation turn.

    Args:
        customer_id: tenancy scope. Required.
        question_text: the user's question. Becomes the routing key
            (encoded into `summary_vector`).
        answer_text: the verified-correct answer prose. Stored as
            `summary_text` for text injection; encoded into
            `answer_embedding_native` for the synthesis path.
        answer_value: the canonical short answer string for the
            cache-hit short-circuit. None when the answer doesn't
            have a single canonical short form (long-form prose
            answers, narrative responses, etc.).
        verified_correct: MUST be True. Caller asserts the answer
            was verified by user thumbs-up, human review, or
            automated assertion. The crystallizer does NOT derive
            verification.
        store: MetadataStore for the upsert.
        encoder: TextEncoder for both summary_vector (P-projected
            HDC) and answer_embedding_native (raw 768-dim, when the
            encoder exposes encode_native).
        tool_outputs: optional iterable of ToolOutput. Web-search and
            code-execution outputs become additional crystals in the
            same call. Passed through verbatim from upstream.
        quality_tier: starting tier. Defaults to "neutral" — the
            quality gate moves crystals to whitelist/quarantine
            based on shadow-eval results. Don't pass "whitelist"
            without an explicit reason.

    Returns:
        List of persisted Crystal rows (1 reasoning crystal + 0..N
        tool-derived crystals). The list is in write order.

    Raises:
        ValueError: if `verified_correct` is not True, or if either
            text is empty after stripping, or if customer_id is empty.
    """
    if not verified_correct:
        raise ValueError(
            "crystallize_success requires verified_correct=True. "
            "Production callers must assert verification via thumbs-up "
            "feedback, human review, or automated assertion. The "
            "crystallizer does not derive verification from internal "
            "state."
        )
    if not customer_id or not customer_id.strip():
        raise ValueError("customer_id is required")
    if not question_text or not question_text.strip():
        raise ValueError("question_text is required")
    if not answer_text or not answer_text.strip():
        raise ValueError("answer_text is required")

    # Build the reasoning crystal. Truncate from the END so we keep the
    # convergence rather than the exploration. (For short answers this
    # is a no-op.) The verified-correct invariant is what gates whether
    # a crystal gets written; we don't second-guess length here. A
    # short verified answer like "Paris" is exactly the kind of signal
    # the cache short-circuit fires on.
    payload = answer_text[-_MAX_CONTENT_CHARS:]

    reasoning_crystal = await run_encoder_bound(
        _build_crystal_row,
        customer_id=customer_id,
        prompt_text=question_text,
        payload_text=payload,
        source_kind="model_reasoning",
        answer_value=answer_value,
        encoder=encoder,
        quality_tier=quality_tier,
    )
    await store.upsert_crystal(reasoning_crystal)

    written: list[Crystal] = [reasoning_crystal]

    # Optional tool-derived crystals. Only on the success path —
    # see the module docstring rationale.
    if tool_outputs:
        seen_urls: set[str] = set()
        for tool_call in tool_outputs:
            if tool_call.name == "web_search":
                for title, url in extract_web_search_provenance(tool_call):
                    if url in seen_urls:
                        continue
                    content = f"{title} \u2014 {url}"
                    if len(content) < _MIN_TOOL_CONTENT_CHARS:
                        continue
                    seen_urls.add(url)
                    web_crystal = await run_encoder_bound(
                        _build_crystal_row,
                        customer_id=customer_id,
                        prompt_text=question_text,
                        payload_text=content,
                        source_kind="web_search_result",
                        answer_value=None,
                        encoder=encoder,
                        quality_tier=quality_tier,
                    )
                    await store.upsert_crystal(web_crystal)
                    written.append(web_crystal)
            elif tool_call.name in ("code_execution", "bash_code_execution"):
                stdout = extract_code_exec_output(tool_call)
                if not stdout or len(stdout) < _MIN_TOOL_CONTENT_CHARS:
                    continue
                truncated = stdout[-_MAX_CONTENT_CHARS:]
                code = (
                    tool_call.input.get("command", "")
                    or tool_call.input.get("code", "")
                )
                content = (
                    f"Code:\n{code[:1000]}\n\nOutput:\n{truncated}"
                    if code
                    else truncated
                )
                code_crystal = await run_encoder_bound(
                    _build_crystal_row,
                    customer_id=customer_id,
                    prompt_text=question_text,
                    payload_text=content,
                    source_kind="code_execution_result",
                    answer_value=None,
                    encoder=encoder,
                    quality_tier=quality_tier,
                )
                await store.upsert_crystal(code_crystal)
                written.append(code_crystal)

    logger.info(
        "crystallize_success_done",
        customer_id=customer_id,
        crystals_written=len(written),
        has_answer_value=answer_value is not None,
    )
    return written


# ---------------------------------------------------------------------------
# Public API — failure path
# ---------------------------------------------------------------------------

async def crystallize_failure(
    *,
    customer_id: str,
    question_text: str,
    wrong_answer: str,
    failed_reasoning: str,
    store: MetadataStore,
    encoder: TextEncoder,
    reflection_client: Optional[ReflectionClient] = None,
) -> Optional[Crystal]:
    """Crystallize a wrong-answer attempt as an imperative rule.

    Generates a reflection (one Haiku call) when reflection_client is
    provided; falls back to the raw end-truncated trace when it isn't.
    Either way the resulting crystal is tagged `failed_reasoning` so
    downstream injection uses imperative voicing.

    Args:
        customer_id: tenancy scope. Required.
        question_text: the user's question. Becomes the routing key.
        wrong_answer: the answer the model produced that the user
            (or evaluator) flagged as wrong.
        failed_reasoning: the model's reasoning trace that led to
            wrong_answer. Used as input to the reflector and as the
            fallback payload when reflection isn't available.
        store: MetadataStore for the upsert.
        encoder: TextEncoder. Same role as in crystallize_success.
        reflection_client: optional override for the reflection LLM
            client. When None, the provider-neutral seam is used
            (get_llm_client). Reflection is skipped and the raw trace
            stored only when no provider is configured or the call fails.

    Returns:
        The persisted Crystal, or None if the inputs were too short
        to produce a useful crystal.

    Raises:
        ValueError: if customer_id, question_text, wrong_answer, or
            failed_reasoning is empty.
    """
    if not customer_id or not customer_id.strip():
        raise ValueError("customer_id is required")
    if not question_text or not question_text.strip():
        raise ValueError("question_text is required")
    if not wrong_answer or not wrong_answer.strip():
        raise ValueError(
            "wrong_answer is required. Failure crystals authored from "
            "empty wrong_answer produce useless reflections."
        )
    if not failed_reasoning or not failed_reasoning.strip():
        raise ValueError(
            "failed_reasoning is required. Failure crystals authored "
            "from empty traces produce useless reflections."
        )

    payload: Optional[str] = None

    # Try the reflection path when an override is passed or the seam is ready.
    if reflection_client is not None or get_llm_client().is_ready():
        rule = _reflect_on_failure(
            question_text=question_text,
            failed_reasoning=failed_reasoning,
            wrong_answer=wrong_answer,
            client=reflection_client,
        )
        if rule and len(rule) >= _MIN_FALLBACK_CHARS:
            payload = rule

    # Fallback: end-truncated raw trace.
    if payload is None:
        truncated = failed_reasoning[-_MAX_CONTENT_CHARS:]
        if len(truncated) < _MIN_FALLBACK_CHARS:
            logger.info(
                "crystallize_failure_skipped_short_trace",
                customer_id=customer_id,
                trace_len=len(truncated),
            )
            return None
        payload = truncated

    failure_crystal = await run_encoder_bound(
        _build_crystal_row,
        customer_id=customer_id,
        prompt_text=question_text,
        payload_text=payload,
        source_kind="failed_reasoning",
        answer_value=None,  # failure crystals don't cache-short-circuit
        encoder=encoder,
        quality_tier="neutral",
    )
    await store.upsert_crystal(failure_crystal)

    logger.info(
        "crystallize_failure_done",
        customer_id=customer_id,
        used_reflection=payload != failed_reasoning[-_MAX_CONTENT_CHARS:],
        crystal_id=failure_crystal.id,
    )
    return failure_crystal


# ---------------------------------------------------------------------------
# Internal: build a Crystal row with encoder-produced vectors
# ---------------------------------------------------------------------------

def _build_crystal_row(
    *,
    customer_id: str,
    prompt_text: str,
    payload_text: str,
    source_kind: str,
    answer_value: Optional[str],
    encoder: TextEncoder,
    quality_tier: str,
) -> Crystal:
    """Construct a Crystal pydantic with vectors filled in by the encoder.

    Mirrors `import_bank.py::_record_to_crystal`. The summary_vector is
    the prompt-projection (so M2 cosine routes by query↔question
    similarity); answer_embedding_native is the answer's raw 768-dim
    embedding (so the synthesis path can reverse-project + decode).

    For hash-encoder banks, encode_native is unavailable and
    answer_embedding_native stays None — those crystals route fine but
    can't participate in synthesis.

    Phase 0.2 keeps the GAIA-style "one crystal per (prompt, answer)"
    shape. Phase 1.1 will additionally call store.add_pair_to_crystal
    on the same crystal_id to populate the codebook with bind/bundle
    math; the crystallizer's public interface won't change.
    """
    crystal_id = f"crys_{uuid.uuid4().hex[:16]}"

    summary_vector = encoder.encode(prompt_text).tolist()
    answer_embedding_native: Optional[list[float]] = None
    if hasattr(encoder, "encode_native"):
        try:
            native = encoder.encode_native(payload_text)  # type: ignore[attr-defined]
            answer_embedding_native = native.tolist()
        except Exception as exc:
            # Don't let a native-encode failure block the crystal write.
            # The crystal can still route via summary_vector; it just
            # can't participate in synthesis.
            logger.warning(
                "encode_native_failed",
                error_type=type(exc).__name__,
                error=str(exc),
            )

    return Crystal(
        id=crystal_id,
        customer_id=customer_id,
        summary_vector=summary_vector,
        answer_embedding_native=answer_embedding_native,
        summary_text=payload_text,
        source_kind=source_kind,  # type: ignore[arg-type]
        answer_value=answer_value,
        quality_tier=quality_tier,  # type: ignore[arg-type]
        keyword_fingerprint=[],  # populated later by the diagnostic engine
        fact_count=0,  # Phase 1.1 will increment via add_pair_to_crystal
    )
