"""baseline schema

Revision ID: 81cf707a1672
Revises: 
Create Date: 2026-06-08 13:28:34.119815

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81cf707a1672'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cognition_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('result_crystal_id', sa.String(length=64), nullable=True),
    sa.Column('source_query_id', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cognition_tasks_customer_id'), 'cognition_tasks', ['customer_id'], unique=False)
    op.create_table('crystal_types',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('capacity_default', sa.Integer(), server_default='50', nullable=False),
    sa.Column('autosplit_policy', sa.String(length=32), server_default='split', nullable=False),
    sa.Column('routing_threshold', sa.Float(), nullable=True),
    sa.Column('cleanup_threshold', sa.Float(), nullable=True),
    sa.Column('pair_schema_dsl', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=False),
    sa.Column('model_routing_config', sa.JSON(), nullable=False),
    sa.Column('injection_preference', sa.String(length=32), nullable=False),
    sa.Column('shadow_sample_rate', sa.Float(), nullable=False),
    sa.Column('retention_policy', sa.Text(), nullable=True),
    sa.Column('billing_config', sa.Text(), nullable=True),
    sa.Column('routing_context_window', sa.Integer(), nullable=True),
    sa.Column('shadow_max_per_day', sa.Integer(), nullable=True),
    sa.Column('general_crystal_types', sa.JSON(), server_default='["general:legacy"]', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('knowledge_gaps',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('missing', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('filled_by_crystal_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_gaps_customer_id'), 'knowledge_gaps', ['customer_id'], unique=False)
    op.create_table('phi_access_log',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=256), nullable=False),
    sa.Column('resource_name', sa.String(length=512), nullable=True),
    sa.Column('contains_phi', sa.Boolean(), nullable=False),
    sa.Column('source_connection_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_phi_access_customer', 'phi_access_log', ['customer_id'], unique=False)
    op.create_index('idx_phi_access_timestamp', 'phi_access_log', ['customer_id', 'timestamp'], unique=False)
    op.create_table('push_review_queue',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('crystal_id', sa.String(length=64), nullable=True),
    sa.Column('source_query_id', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_review_queue_customer_id'), 'push_review_queue', ['customer_id'], unique=False)
    op.create_table('baa_tracking',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('baa_signed', sa.Boolean(), nullable=False),
    sa.Column('baa_signed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baa_document_ref', sa.String(length=512), nullable=True),
    sa.Column('phi_data_sources', sa.JSON(), nullable=True),
    sa.Column('hipaa_contact_email', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('blacklisted_reflections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('reflection_hash', sa.String(length=64), nullable=False),
    sa.Column('reflection_text', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blacklisted_customer', 'blacklisted_reflections', ['customer_id'], unique=False)
    op.create_index('idx_blacklisted_hash', 'blacklisted_reflections', ['customer_id', 'reflection_hash'], unique=True)
    op.create_table('critic_calibrations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('critic_role', sa.String(length=32), nullable=False),
    sa.Column('critic_model', sa.String(length=128), nullable=False),
    sa.Column('total_proposals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('promoted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deferred_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dropped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_synthesis_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_critic_calibrations_customer_id'), 'critic_calibrations', ['customer_id'], unique=False)
    op.create_index('ux_critic_calibrations_identity', 'critic_calibrations', ['customer_id', 'critic_role', 'critic_model'], unique=True)
    op.create_table('critique_syntheses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('review_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_item_ids', sa.JSON(), nullable=False),
    sa.Column('deferred_item_ids', sa.JSON(), nullable=False),
    sa.Column('dropped_item_ids', sa.JSON(), nullable=False),
    sa.Column('promotion_rationales', sa.JSON(), nullable=False),
    sa.Column('critic_calibration_updates', sa.JSON(), nullable=False),
    sa.Column('cross_trace_patterns', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_critique_syntheses_customer_created', 'critique_syntheses', ['customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_critique_syntheses_customer_id'), 'critique_syntheses', ['customer_id'], unique=False)
    op.create_index('ix_critique_syntheses_trace_created', 'critique_syntheses', ['trace_id', 'created_at'], unique=False)
    op.create_table('critiques',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('sequence_id', sa.String(length=64), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=True),
    sa.Column('critic_role', sa.String(length=32), nullable=False),
    sa.Column('critic_model', sa.String(length=128), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('total_action_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_critiques_customer_id'), 'critiques', ['customer_id'], unique=False)
    op.create_index('ix_critiques_role_created', 'critiques', ['customer_id', 'critic_role', 'created_at'], unique=False)
    op.create_index('ix_critiques_sequence', 'critiques', ['customer_id', 'sequence_id', 'turn_index'], unique=False)
    op.create_index('ix_critiques_trace', 'critiques', ['trace_id'], unique=False)
    op.create_table('crystals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('summary_vector', sa.JSON(), nullable=False),
    sa.Column('routing_vector', sa.JSON(), nullable=True),
    sa.Column('answer_embedding_native', sa.JSON(), nullable=True),
    sa.Column('encoder_fingerprint', sa.Text(), nullable=True),
    sa.Column('source_kind', sa.String(length=32), server_default='model_reasoning', nullable=False),
    sa.Column('answer_value', sa.Text(), nullable=True),
    sa.Column('decay_rate', sa.Float(), nullable=False),
    sa.Column('fact_count', sa.Integer(), nullable=False),
    sa.Column('quality_tier', sa.String(length=32), nullable=False),
    sa.Column('eval_helped_count', sa.Integer(), nullable=False),
    sa.Column('eval_hurt_count', sa.Integer(), nullable=False),
    sa.Column('live_shadow_helped_count', sa.Integer(), nullable=False),
    sa.Column('live_shadow_hurt_count', sa.Integer(), nullable=False),
    sa.Column('keyword_fingerprint', sa.JSON(), nullable=False),
    sa.Column('cluster_tightness', sa.Float(), nullable=True),
    sa.Column('attribution_spread', sa.Float(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('build_method', sa.String(length=32), nullable=False),
    sa.Column('parent_crystal_id', sa.String(length=64), nullable=True),
    sa.Column('source_path', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('crystal_type', sa.String(length=128), server_default='customer:legacy', nullable=False),
    sa.Column('decomposer_payload', sa.JSON(), nullable=True),
    sa.Column('diagnostic_tags', sa.JSON(), nullable=False),
    sa.Column('last_eval_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['parent_crystal_id'], ['crystals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crystals_customer_id'), 'crystals', ['customer_id'], unique=False)
    op.create_index('ix_crystals_customer_tier', 'crystals', ['customer_id', 'quality_tier'], unique=False)
    op.create_index('ix_crystals_customer_type', 'crystals', ['customer_id', 'crystal_type'], unique=False)
    op.create_index(op.f('ix_crystals_quality_tier'), 'crystals', ['quality_tier'], unique=False)
    op.create_table('document_uploads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('crystal_type', sa.String(length=128), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('crystals_written', sa.Integer(), nullable=False),
    sa.Column('items_extracted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('crystallized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_file_id', sa.String(length=256), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_connection_id', sa.String(length=64), nullable=True),
    sa.Column('extracted_items', sa.JSON(), nullable=True),
    sa.Column('detected_type', sa.String(length=64), nullable=True),
    sa.Column('confirmed_type', sa.String(length=64), nullable=True),
    sa.Column('content_chunks', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_uploads_source_file', 'document_uploads', ['customer_id', 'source_file_id'], unique=False)
    op.create_index('idx_document_uploads_customer', 'document_uploads', ['customer_id'], unique=False)
    op.create_index('idx_document_uploads_status', 'document_uploads', ['customer_id', 'status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('facts_extracted_count', sa.Integer(), nullable=False),
    sa.Column('facts_verified_count', sa.Integer(), nullable=False),
    sa.Column('facts_rejected_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_customer_id'), 'documents', ['customer_id'], unique=False)
    op.create_table('drive_connections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('token_nonce', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dsl_configs',
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'name')
    )
    op.create_table('feedback',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('sequence_id', sa.String(length=64), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('signal', sa.String(length=8), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_customer', 'feedback', ['customer_id', 'created_at'], unique=False)
    op.create_index('ix_feedback_sequence', 'feedback', ['customer_id', 'sequence_id', 'turn_index'], unique=False)
    op.create_table('mandatory_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('unless_clause', sa.Text(), nullable=True),
    sa.Column('source_round', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mandatory_rules_customer', 'mandatory_rules', ['customer_id'], unique=False)
    op.create_table('meta_patterns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('pattern_text', sa.Text(), nullable=False),
    sa.Column('affected_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meta_patterns_customer', 'meta_patterns', ['customer_id'], unique=False)
    op.create_table('verification_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_claim', sa.Text(), nullable=False),
    sa.Column('candidate_vector', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tasks_customer_id'), 'verification_tasks', ['customer_id'], unique=False)
    op.create_index(op.f('ix_verification_tasks_status'), 'verification_tasks', ['status'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('critique_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('critic_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('metacog_decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acted_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['critique_id'], ['critiques.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_critique_id'), 'action_items', ['critique_id'], unique=False)
    op.create_index(op.f('ix_action_items_customer_id'), 'action_items', ['customer_id'], unique=False)
    op.create_index('ix_action_items_customer_status', 'action_items', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('ix_action_items_status'), 'action_items', ['status'], unique=False)
    op.create_index('ix_action_items_type_status', 'action_items', ['action_type', 'status'], unique=False)
    op.create_table('crystal_acls',
    sa.Column('crystal_id', sa.String(length=64), nullable=False),
    sa.Column('principal_type', sa.String(length=32), nullable=False),
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('grant', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crystal_id'], ['crystals.id'], ),
    sa.PrimaryKeyConstraint('crystal_id', 'principal_type', 'principal_id', 'grant')
    )
    op.create_index('ix_crystal_acls_principal', 'crystal_acls', ['principal_type', 'principal_id'], unique=False)
    op.create_table('crystal_chains',
    sa.Column('source_crystal_id', sa.String(length=64), nullable=False),
    sa.Column('target_crystal_id', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=32), server_default='source_uses_target', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_crystal_id'], ['crystals.id'], ),
    sa.ForeignKeyConstraint(['target_crystal_id'], ['crystals.id'], ),
    sa.PrimaryKeyConstraint('source_crystal_id', 'target_crystal_id')
    )
    op.create_index('ix_crystal_chains_target', 'crystal_chains', ['target_crystal_id'], unique=False)
    op.create_table('crystal_diagnostics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('crystal_id', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure_mode_distribution', sa.JSON(), nullable=False),
    sa.Column('top_help_query_exemplars', sa.JSON(), nullable=False),
    sa.Column('top_hurt_query_exemplars', sa.JSON(), nullable=False),
    sa.Column('compression_ratio_p25', sa.Float(), nullable=True),
    sa.Column('compression_ratio_p50', sa.Float(), nullable=True),
    sa.Column('compression_ratio_p75', sa.Float(), nullable=True),
    sa.Column('query_distribution_drift', sa.Float(), nullable=True),
    sa.Column('proposed_edit_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['crystal_id'], ['crystals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crystal_diagnostics_crystal_id'), 'crystal_diagnostics', ['crystal_id'], unique=False)
    op.create_table('crystal_edges',
    sa.Column('crystal_a_id', sa.String(length=64), nullable=False),
    sa.Column('crystal_b_id', sa.String(length=64), nullable=False),
    sa.Column('edge_type', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('last_reinforced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crystal_a_id'], ['crystals.id'], ),
    sa.ForeignKeyConstraint(['crystal_b_id'], ['crystals.id'], ),
    sa.PrimaryKeyConstraint('crystal_a_id', 'crystal_b_id', 'edge_type')
    )
    op.create_table('crystal_edits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('crystal_id', sa.String(length=64), nullable=False),
    sa.Column('edit_type', sa.String(length=32), nullable=False),
    sa.Column('proposed_by', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('affected_facts', sa.JSON(), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_impact', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crystal_id'], ['crystals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crystal_edits_crystal_id'), 'crystal_edits', ['crystal_id'], unique=False)
    op.create_index(op.f('ix_crystal_edits_status'), 'crystal_edits', ['status'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('crystal_id', sa.String(length=64), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('pair_type', sa.String(length=64), server_default='question_answer', nullable=False),
    sa.Column('source_kind', sa.String(length=32), server_default='model_reasoning', nullable=False),
    sa.Column('answer_value', sa.Text(), nullable=True),
    sa.Column('prompt_text', sa.Text(), server_default='', nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('source_doc_id', sa.String(length=64), nullable=True),
    sa.Column('extracted_by', sa.String(length=128), nullable=True),
    sa.Column('verified_by', sa.String(length=128), nullable=True),
    sa.Column('grating_strength', sa.Float(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crystal_id'], ['crystals.id'], ),
    sa.ForeignKeyConstraint(['source_doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_crystal_id'), 'facts', ['crystal_id'], unique=False)
    op.create_index(op.f('ix_facts_pair_type'), 'facts', ['pair_type'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_vector', sa.JSON(), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('injection_method', sa.String(length=32), nullable=False),
    sa.Column('confidence_gate_fires', sa.Integer(), nullable=False),
    sa.Column('matched_facts', sa.JSON(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_confidence_at_commit', sa.Float(), nullable=True),
    sa.Column('upstream_call_made', sa.Boolean(), nullable=False),
    sa.Column('shadow_ran', sa.Boolean(), nullable=False),
    sa.Column('shadow_delta', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('shadow_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('shadow_completion_tokens', sa.Integer(), nullable=True),
    sa.Column('prompt_token_overhead', sa.Integer(), nullable=True),
    sa.Column('concept_top_config', sa.String(length=128), nullable=True),
    sa.Column('concept_top_score', sa.Float(), nullable=True),
    sa.Column('concept_payload', sa.JSON(), nullable=True),
    sa.Column('sequence_id', sa.String(length=64), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=True),
    sa.Column('routed_crystal_id', sa.String(length=64), nullable=True),
    sa.Column('top1_score', sa.Float(), nullable=True),
    sa.Column('top2_score', sa.Float(), nullable=True),
    sa.Column('sparse_key', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['routed_crystal_id'], ['crystals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_logs_customer_id'), 'query_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_query_logs_match_type'), 'query_logs', ['match_type'], unique=False)
    op.create_index('ix_query_logs_sequence', 'query_logs', ['customer_id', 'sequence_id', 'turn_index'], unique=False)
    op.create_index(op.f('ix_query_logs_timestamp'), 'query_logs', ['timestamp'], unique=False)
    op.create_table('watched_files',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=256), nullable=True),
    sa.Column('contains_phi', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['drive_connections.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watched_folders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('folder_id', sa.String(length=256), nullable=False),
    sa.Column('folder_name', sa.String(length=512), nullable=False),
    sa.Column('folder_path', sa.Text(), nullable=True),
    sa.Column('contains_phi', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_file_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['drive_connections.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_alignments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('focus_item_id', sa.String(length=64), nullable=False),
    sa.Column('alignment_class', sa.String(length=32), nullable=False),
    sa.Column('paired_item_ids', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['focus_item_id'], ['action_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_alignments_customer_id'), 'item_alignments', ['customer_id'], unique=False)
    op.create_index('ix_item_alignments_focus_item', 'item_alignments', ['focus_item_id'], unique=False)
    op.create_index('ix_item_alignments_trace', 'item_alignments', ['trace_id'], unique=False)
    op.create_table('reasoning_traces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('sequence_id', sa.String(length=64), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=True),
    sa.Column('query_log_id', sa.String(length=64), nullable=True),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('crystals_used', sa.JSON(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('inferences', sa.JSON(), nullable=False),
    sa.Column('borders_crossed', sa.JSON(), nullable=False),
    sa.Column('gaps_felt', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['query_log_id'], ['query_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reasoning_traces_customer_created', 'reasoning_traces', ['customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reasoning_traces_customer_id'), 'reasoning_traces', ['customer_id'], unique=False)
    op.create_index('ix_reasoning_traces_sequence', 'reasoning_traces', ['customer_id', 'sequence_id', 'turn_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reasoning_traces_sequence', table_name='reasoning_traces')
    op.drop_index(op.f('ix_reasoning_traces_customer_id'), table_name='reasoning_traces')
    op.drop_index('ix_reasoning_traces_customer_created', table_name='reasoning_traces')
    op.drop_table('reasoning_traces')
    op.drop_index('ix_item_alignments_trace', table_name='item_alignments')
    op.drop_index('ix_item_alignments_focus_item', table_name='item_alignments')
    op.drop_index(op.f('ix_item_alignments_customer_id'), table_name='item_alignments')
    op.drop_table('item_alignments')
    op.drop_table('watched_folders')
    op.drop_table('watched_files')
    op.drop_index(op.f('ix_query_logs_timestamp'), table_name='query_logs')
    op.drop_index('ix_query_logs_sequence', table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_match_type'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_customer_id'), table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_facts_pair_type'), table_name='facts')
    op.drop_index(op.f('ix_facts_crystal_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_crystal_edits_status'), table_name='crystal_edits')
    op.drop_index(op.f('ix_crystal_edits_crystal_id'), table_name='crystal_edits')
    op.drop_table('crystal_edits')
    op.drop_table('crystal_edges')
    op.drop_index(op.f('ix_crystal_diagnostics_crystal_id'), table_name='crystal_diagnostics')
    op.drop_table('crystal_diagnostics')
    op.drop_index('ix_crystal_chains_target', table_name='crystal_chains')
    op.drop_table('crystal_chains')
    op.drop_index('ix_crystal_acls_principal', table_name='crystal_acls')
    op.drop_table('crystal_acls')
    op.drop_index('ix_action_items_type_status', table_name='action_items')
    op.drop_index(op.f('ix_action_items_status'), table_name='action_items')
    op.drop_index('ix_action_items_customer_status', table_name='action_items')
    op.drop_index(op.f('ix_action_items_customer_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_critique_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_verification_tasks_status'), table_name='verification_tasks')
    op.drop_index(op.f('ix_verification_tasks_customer_id'), table_name='verification_tasks')
    op.drop_table('verification_tasks')
    op.drop_index('idx_meta_patterns_customer', table_name='meta_patterns')
    op.drop_table('meta_patterns')
    op.drop_index('idx_mandatory_rules_customer', table_name='mandatory_rules')
    op.drop_table('mandatory_rules')
    op.drop_index('ix_feedback_sequence', table_name='feedback')
    op.drop_index('ix_feedback_customer', table_name='feedback')
    op.drop_table('feedback')
    op.drop_table('dsl_configs')
    op.drop_table('drive_connections')
    op.drop_index(op.f('ix_documents_customer_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_document_uploads_status', table_name='document_uploads')
    op.drop_index('idx_document_uploads_customer', table_name='document_uploads')
    op.drop_index('idx_doc_uploads_source_file', table_name='document_uploads')
    op.drop_table('document_uploads')
    op.drop_index(op.f('ix_crystals_quality_tier'), table_name='crystals')
    op.drop_index('ix_crystals_customer_type', table_name='crystals')
    op.drop_index('ix_crystals_customer_tier', table_name='crystals')
    op.drop_index(op.f('ix_crystals_customer_id'), table_name='crystals')
    op.drop_table('crystals')
    op.drop_index('ix_critiques_trace', table_name='critiques')
    op.drop_index('ix_critiques_sequence', table_name='critiques')
    op.drop_index('ix_critiques_role_created', table_name='critiques')
    op.drop_index(op.f('ix_critiques_customer_id'), table_name='critiques')
    op.drop_table('critiques')
    op.drop_index('ix_critique_syntheses_trace_created', table_name='critique_syntheses')
    op.drop_index(op.f('ix_critique_syntheses_customer_id'), table_name='critique_syntheses')
    op.drop_index('ix_critique_syntheses_customer_created', table_name='critique_syntheses')
    op.drop_table('critique_syntheses')
    op.drop_index('ux_critic_calibrations_identity', table_name='critic_calibrations')
    op.drop_index(op.f('ix_critic_calibrations_customer_id'), table_name='critic_calibrations')
    op.drop_table('critic_calibrations')
    op.drop_index('idx_blacklisted_hash', table_name='blacklisted_reflections')
    op.drop_index('idx_blacklisted_customer', table_name='blacklisted_reflections')
    op.drop_table('blacklisted_reflections')
    op.drop_table('baa_tracking')
    op.drop_index(op.f('ix_push_review_queue_customer_id'), table_name='push_review_queue')
    op.drop_table('push_review_queue')
    op.drop_index('idx_phi_access_timestamp', table_name='phi_access_log')
    op.drop_index('idx_phi_access_customer', table_name='phi_access_log')
    op.drop_table('phi_access_log')
    op.drop_index(op.f('ix_knowledge_gaps_customer_id'), table_name='knowledge_gaps')
    op.drop_table('knowledge_gaps')
    op.drop_table('customers')
    op.drop_table('crystal_types')
    op.drop_index(op.f('ix_cognition_tasks_customer_id'), table_name='cognition_tasks')
    op.drop_table('cognition_tasks')
    # ### end Alembic commands ###
